config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :agents

  resources :customers

  root 'agents#index'


end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :customer 
	belongs_to :agent

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    @message.to = message_params[:to]
    @message.from = message_params[:from]
    @message.text = message_params[:text]

    @agent = Agent.where(:bw_phone_number => message_params[:to]).first

    @message.agent_id = @agent.id

    # this SMS is from a customer, find the agent and forward it
    if @message.from != @agent.agent_phone_number

      @customer = Customer.where(:phone_number => @message.from, :agent_id => @agent.id).first_or_create
      @message.customer_id = @customer.id
      @message.msg_type = 'customer'

      Bandwidth::Message.create(
          :from => @agent.bw_phone_number,
          :to => @agent.agent_phone_number,
          :text => @customer.id.to_s + ": " + @message.text
      )

    # this SMS is from a agent, send it to the customer  
    elsif @message.from == @agent.agent_phone_number 

        # look for a id: at the beginning of message
        if /\d:/.match(@message.text)

            _tmp_customer = /\d+:/.match(@message.text).to_s            
            _tmp_customer_id = /\d+/.match(_tmp_customer).to_s


            if !Customer.find_by_id(_tmp_customer_id.to_i).nil?

              @customer = Customer.find(_tmp_customer_id.to_i)

              # parse message and remove id: field
              Bandwidth::Message.create(
                :from => @agent.bw_phone_number,
                :to => @customer.phone_number,
                :text => @message.text.gsub(/\d+:/, '')
              )

              # clean up and record response in database
              @message.msg_type = 'agent_reply'
              @message.text = @message.text.gsub(/\d+:/, '')
              @message.from = @agent.bw_phone_number
              @message.to = @customer.phone_number
              @message.customer_id = @customer.id
              
            else # no customer found, send agent an error back

              Bandwidth::Message.create(
                :from => @agent.bw_phone_number,
                :to => @agent.agent_phone_number,
                :text => "Sorry, that customer id was not found, can you check again and reply with id:, for example '1: your message'"
              )

              # clean up and record response in database
              @message.msg_type = 'reply_error_no_customer_found'
              @message.text = @message.text.gsub(/\d+:/, '')
              @message.from = @agent.bw_phone_number
              @message.to = @agent.agent_phone_number

            end

        else # forgot to tell us who to send to, give them instructions back

          Bandwidth::Message.create(
            :from => @agent.bw_phone_number,
            :to => @agent.agent_phone_number,
            :text => 'When replying to a customer, first include the customer id, for example put 1: at the start of your reply message and we will send to that customer.'
          )

          @message.msg_type = 'reply_error_no_id_included'

        end

    end


    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:to, :from, :agent_id, :customer_id, :text, :msg_type)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for @message, :html => { :class => "form-horizontal message" } do |f| %>

    <% if @message.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :to, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:to]) %>
  </div>
  <div class="control-group">
    <%= f.label :from, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:from]) %>
  </div>
  <div class="control-group">
    <%= f.label :agent_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :agent_id, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:agent_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :customer_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_id, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:customer_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :text, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:text]) %>
  </div>
  <div class="control-group">
    <%= f.label :msg_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :msg_type, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:msg_type]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            messages_path, :class => 'btn btn-default' %>

<% end %>

app/views/messages/edit.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:from) %></th>
      <th><%= model_class.human_attribute_name(:agent_id) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:msg_type) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to message.id, message_path(message) %></td>
        <td><%= message.to %></td>
        <td><%= message.from %></td>
        <td><%= message.agent_id %></td>
        <td><%= message.customer_id %></td>
        <td><%= message.text %></td>
        <td><%= message.msg_type %></td>
        <td><%=l message.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_message_path(message), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      message_path(message),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>

app/views/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
  <dd><%= @message.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @message.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:agent_id) %>:</strong></dt>
  <dd><%= @message.agent_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @message.customer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @message.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:msg_type) %>:</strong></dt>
  <dd><%= @message.msg_type %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              messages_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_message_path(@message), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>