config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :agents

  resources :customers

  root 'agents#index'


end

app/models/agent.rb
class Agent < ActiveRecord::Base

	has_many :messages
	has_many :customers

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit(:bw_phone_number, :agent_phone_number)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_form.html.erb
<%= form_for @agent, :html => { :class => "form-horizontal agent" } do |f| %>

    <% if @agent.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @agent.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :bw_phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bw_phone_number, :class => 'form-control' %>
    </div>
    <%= error_span(@agent[:bw_phone_number]) %>
  </div>
  <div class="control-group">
    <%= f.label :agent_phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :agent_phone_number, :class => 'form-control' %>
    </div>
    <%= error_span(@agent[:agent_phone_number]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            agents_path, :class => 'btn btn-default' %>

<% end %>

app/views/agents/edit.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agents/index.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:bw_phone_number) %></th>
      <th><%= model_class.human_attribute_name(:agent_phone_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= link_to agent.id, agent_path(agent) %></td>
        <td><%= agent.bw_phone_number %></td>
        <td><%= agent.agent_phone_number %></td>
        <td><%=l agent.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_agent_path(agent), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      agent_path(agent),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_agent_path,
            :class => 'btn btn-primary' %>

app/views/agents/new.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agents/show.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:bw_phone_number) %>:</strong></dt>
  <dd><%= @agent.bw_phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:agent_phone_number) %>:</strong></dt>
  <dd><%= @agent.agent_phone_number %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              agents_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_agent_path(@agent), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              agent_path(@agent),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>